import React from 'react';
import type { ReportItem } from '@/types/reports';
import { StatePlaceholder, type ViewState } from '@/components/shared/StatePlaceholder';

interface ReportsTableProps {
  reports: ReportItem[];
  viewState: ViewState;
  onSelect: (report: ReportItem) => void;
  currentPage: number;
  totalPages: number;
  totalEntries: number;
  limit: number;
  onPageChange: (page: number) => void;
}

export const ReportsTable: React.FC<ReportsTableProps> = ({
  reports,
  viewState,
  onSelect,
  currentPage,
  totalPages,
  totalEntries,
  limit,
  onPageChange
}) => {
  const startIndex = (currentPage - 1) * limit;
  const endIndex = Math.min(startIndex + limit, totalEntries);

  const handlePageChange = (page: number) => {
    if (page >= 1 && page <= totalPages) {
      onPageChange(page);
    }
  };

  const getStatusStyle = (status: ReportItem['status']) => {
    switch (status) {
      case 'COMPLETED':
        return 'bg-success-bg text-success-text border-success/20';
      case 'PENDING':
        return 'bg-warning-bg text-warning-text border-warning/20';
      case 'FAILED':
        return 'bg-danger-bg text-danger-text border-danger/20';
      default:
        return 'bg-surface-container text-on-surface border-outline-variant/30';
    }
  };

  const handleDownload = (e: React.MouseEvent, name: string) => {
    e.stopPropagation();
    alert(`Downloading ${name}... (Simulated Action)`);
  };

  return (
    <div className="bg-surface-container-lowest border border-outline-variant rounded-xl overflow-hidden shadow-sm flex flex-col">
      <div className="p-4 border-b border-outline-variant bg-surface-container-low flex justify-between items-center">
        <h3 className="font-headline-md text-headline-md text-primary font-bold">Generated Reports Log</h3>
        <span className="text-body-sm text-on-surface-variant font-medium">History of recent generation requests</span>
      </div>

      <StatePlaceholder state={viewState} emptyMessage="No reports found matching filters.">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <caption className="sr-only"> Narula Institute of Technology generated reports logs list table.</caption>
            <thead>
              <tr className="bg-surface-container-high/40 text-on-surface font-label-md text-label-md border-b border-outline-variant">
                <th className="py-3 px-6 font-medium whitespace-nowrap">Report Name</th>
                <th className="py-3 px-6 font-medium whitespace-nowrap">Type</th>
                <th className="py-3 px-6 font-medium whitespace-nowrap">Period</th>
                <th className="py-3 px-6 font-medium whitespace-nowrap">Generated By</th>
                <th className="py-3 px-6 font-medium whitespace-nowrap">Timestamp</th>
                <th className="py-3 px-6 font-medium whitespace-nowrap">Status</th>
                <th className="py-3 px-6 font-medium whitespace-nowrap text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-outline-variant font-body-sm text-body-sm text-on-surface">
              {reports.map((rep) => (
                <tr
                  key={rep.id}
                  className="hover:bg-surface-container-low transition-colors cursor-pointer"
                  onClick={() => onSelect(rep)}
                >
                  <td className="py-4 px-6 font-medium text-on-surface">{rep.name}</td>
                  <td className="py-4 px-6 text-on-surface-variant whitespace-nowrap">{rep.type}</td>
                  <td className="py-4 px-6 text-on-surface-variant whitespace-nowrap">{rep.dateRange}</td>
                  <td className="py-4 px-6 text-on-surface-variant whitespace-nowrap">{rep.generatedBy}</td>
                  <td className="py-4 px-6 text-on-surface-variant whitespace-nowrap">{rep.lastGenerated}</td>
                  <td className="py-4 px-6 whitespace-nowrap">
                    <span
                      className={`inline-flex items-center px-2.5 py-0.5 rounded-full font-label-sm text-label-sm font-medium border ${getStatusStyle(
                        rep.status
                      )}`}
                    >
                      {rep.status}
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right whitespace-nowrap" onClick={(e) => e.stopPropagation()}>
                    <button
                      aria-label={`Download ${rep.name}`}
                      className="text-primary hover:text-primary-container transition-colors p-1.5 rounded hover:bg-surface-container-low"
                      onClick={(e) => handleDownload(e, rep.name)}
                    >
                      <span className="material-symbols-outlined text-[18px]">download</span>
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {totalEntries > 0 && (
          <div className="px-6 py-4 bg-surface-container-lowest border-t border-outline-variant flex items-center justify-between flex-wrap gap-2">
            <span className="text-body-sm text-on-surface-variant">
              Showing {totalEntries === 0 ? 0 : startIndex + 1}-{endIndex} of {totalEntries} records
            </span>
            <div className="flex gap-2">
              <button
                aria-label="Previous page"
                className="p-1.5 border border-outline-variant rounded-lg hover:bg-surface-container-low disabled:opacity-50 transition-all"
                disabled={currentPage === 1}
                onClick={() => handlePageChange(currentPage - 1)}
              >
                <span className="material-symbols-outlined text-[18px]">chevron_left</span>
              </button>
              <button
                aria-label="Next page"
                className="p-1.5 border border-outline-variant rounded-lg hover:bg-surface-container-low disabled:opacity-50 transition-all"
                disabled={currentPage === totalPages || totalPages === 0}
                onClick={() => handlePageChange(currentPage + 1)}
              >
                <span className="material-symbols-outlined text-[18px]">chevron_right</span>
              </button>
            </div>
          </div>
        )}
      </StatePlaceholder>
    </div>
  );
};
