/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d8e3fb",
        "tertiary": "#393f45",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#0b1c30",
        "surface-container": "#e7eeff",
        "primary": "#263b74",
        "surface-container-high": "#dee8ff",
        "tertiary-fixed": "#dde3eb",
        "error": "#ba1a1a",
        "background": "#f9f9ff",
        "primary-fixed": "#dbe1ff",
        "on-surface": "#111c2d",
        "outline-variant": "#c5c6d1",
        "on-secondary": "#ffffff",
        "outline": "#757681",
        "border": "#c5c6d1",
        "input": "#c5c6d1",
        "ring": "#263b74",
        "foreground": "#111c2d",
        "on-primary": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container": "#eaedf9",
        "success": "#16a34a",
        "success-bg": "#dcfce7",
        "success-text": "#166534",
        "danger": "#dc2626",
        "danger-bg": "#fee2e2",
        "danger-text": "#991b1b",
        "warning": "#d97706",
        "warning-bg": "#fef3c7",
        "warning-text": "#92400e",
        "on-surface-variant": "#444650",
        "on-background": "#111c2d",
        "surface-bright": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "secondary": "#505f76",
        "tertiary-container": "#50565d",
        "primary-container": "#3f538d",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-fixed-dim": "#c1c7cf",
        "inverse-surface": "#263143",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#41474e",
        "on-secondary-container": "#54647a",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d8e3fb",
        "on-tertiary-fixed": "#161c22",
        "surface-tint": "#485c97",
        "inverse-primary": "#b4c5ff",
        "on-secondary-fixed-variant": "#38485d",
        "secondary-fixed": "#d3e4fe",
        "on-primary-container": "#bac9ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#30447d",
        "surface-dim": "#cfdaf2",
        "inverse-on-surface": "#ecf1ff",
        "secondary-container": "#d0e1fb",
        "on-tertiary-container": "#c5cbd3",
        "surface": "#f9f9ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sidebar-width": "280px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "unit": "8px",
        "container-max-width": "1440px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
}
