import React from 'react';
import type { ReportItem } from '@/types/reports';

interface ReportDrawerProps {
  report: ReportItem | null;
  onClose: () => void;
  onExport: (type: string, format: string) => void;
  isExporting?: boolean;
}

export const ReportDrawer: React.FC<ReportDrawerProps> = ({ report, onClose, onExport, isExporting }) => {
  if (!report) return null;

  const handleAction = (format: string) => {
    if (!isExporting) {
      onExport(report.type, format);
    }
  };

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/30 backdrop-blur-xs z-50 transition-opacity duration-300"
        onClick={onClose}
      />

      {/* Drawer Panel */}
      <div className="fixed right-0 top-0 h-full w-full max-w-md bg-surface-container-lowest border-l border-outline-variant shadow-lg z-50 flex flex-col transition-transform duration-300 transform translate-x-0 overflow-y-auto no-scrollbar">
        {/* Header */}
        <div className="px-6 py-5 border-b border-outline-variant flex items-center justify-between">
          <h3 className="font-headline-md text-headline-md text-on-background">Report Preview</h3>
          <button
            aria-label="Close details"
            className="p-1 text-on-surface-variant hover:bg-surface-container rounded-lg transition-all"
            onClick={onClose}
          >
            <span className="material-symbols-outlined">close</span>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 p-6 flex flex-col gap-6 font-body-sm text-body-sm">
          {/* Title and description */}
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <span className="bg-primary-fixed text-primary px-2.5 py-0.5 rounded-full font-label-sm text-label-sm font-bold">
                {report.type}
              </span>
              <span
                className={`px-2 py-0.5 rounded text-[11px] font-bold border ${
                  report.status === 'COMPLETED'
                    ? 'bg-success-bg text-success-text border-success/15'
                    : 'bg-danger-bg text-danger-text border-danger/15'
                }`}
              >
                {report.status}
              </span>
            </div>
            <h4 className="font-headline-md text-headline-md text-on-background font-bold leading-snug">
              {report.name}
            </h4>
            <p className="text-on-surface-variant mt-2 italic leading-relaxed">
              {report.description || 'No report overview details configured.'}
            </p>
          </div>

          {/* Details list */}
          <div className="bg-surface-container-low border border-outline-variant p-4 rounded-lg flex flex-col gap-3">
            <h5 className="font-label-md text-label-md text-primary font-bold">Metadata</h5>
            <div className="grid grid-cols-2 gap-3 font-body-sm text-body-sm text-on-surface">
              <div>
                <span className="block text-on-surface-variant font-label-sm text-label-sm">Report ID</span>
                {report.id}
              </div>
              <div>
                <span className="block text-on-surface-variant font-label-sm text-label-sm">File Size</span>
                {report.sizeBytes}
              </div>
              <div>
                <span className="block text-on-surface-variant font-label-sm text-label-sm">Date Period</span>
                {report.dateRange}
              </div>
              <div>
                <span className="block text-on-surface-variant font-label-sm text-label-sm">Log Entries</span>
                {report.recordsCount ? `${report.recordsCount} records` : '0 entries'}
              </div>
              <div className="col-span-2">
                <span className="block text-on-surface-variant font-label-sm text-label-sm">Generated By</span>
                {report.generatedBy} on {report.lastGenerated}
              </div>
            </div>
          </div>

          {/* Quick preview stats */}
          <div className="bg-surface-container-low border border-outline-variant p-4 rounded-lg flex flex-col gap-3">
            <h5 className="font-label-md text-label-md text-primary font-bold">Summary Preview</h5>
            <div className="grid grid-cols-3 gap-2 text-center">
              <div className="bg-surface p-2.5 rounded border border-outline-variant/30">
                <span className="block text-[10px] text-on-surface-variant font-medium">AVG IN</span>
                <span className="font-bold text-success-text text-sm">94.8%</span>
              </div>
              <div className="bg-surface p-2.5 rounded border border-outline-variant/30">
                <span className="block text-[10px] text-on-surface-variant font-medium">LATE</span>
                <span className="font-bold text-warning-text text-sm">12 avg</span>
              </div>
              <div className="bg-surface p-2.5 rounded border border-outline-variant/30">
                <span className="block text-[10px] text-on-surface-variant font-medium">OVERTIME</span>
                <span className="font-bold text-primary text-sm">4.2 hrs</span>
              </div>
            </div>
          </div>

          {/* Mock charts visualization preview */}
          <div className="bg-surface-container-low border border-outline-variant p-4 rounded-lg">
            <h5 className="font-label-md text-label-md text-primary font-bold mb-3">Preview Trends Chart</h5>
            <div className="h-28 flex items-end justify-between gap-2.5 bg-surface p-3 rounded border border-outline-variant/30">
              <div className="bg-primary/50 hover:bg-primary w-full h-[60%] rounded transition-all" />
              <div className="bg-primary/50 hover:bg-primary w-full h-[75%] rounded transition-all" />
              <div className="bg-primary/50 hover:bg-primary w-full h-[85%] rounded transition-all" />
              <div className="bg-primary/50 hover:bg-primary w-full h-[40%] rounded transition-all" />
              <div className="bg-primary/50 hover:bg-primary w-full h-[90%] rounded transition-all" />
            </div>
          </div>

          {/* Export triggers */}
          <div className="flex gap-3 mt-auto border-t border-outline-variant pt-4 shrink-0">
            <button
              className="flex-1 bg-primary text-on-primary py-2.5 rounded-lg font-label-md text-label-md hover:bg-primary-container transition-colors shadow-sm font-bold flex items-center justify-center gap-1.5 disabled:opacity-60"
              onClick={() => handleAction('PDF')}
              disabled={isExporting}
            >
              {isExporting ? (
                <div className="w-[18px] h-[18px] border-2 border-white border-t-transparent rounded-full animate-spin"></div>
              ) : (
                <span className="material-symbols-outlined text-[18px]">picture_as_pdf</span>
              )}
              PDF
            </button>
            <button
              className="flex-1 bg-white text-secondary border border-outline-variant py-2.5 rounded-lg font-label-md text-label-md hover:bg-surface-container transition-colors font-bold flex items-center justify-center gap-1.5 disabled:opacity-60"
              onClick={() => handleAction('XLSX')}
              disabled={isExporting}
            >
              {isExporting ? (
                <div className="w-[18px] h-[18px] border-2 border-primary border-t-transparent rounded-full animate-spin"></div>
              ) : (
                <span className="material-symbols-outlined text-[18px]">description</span>
              )}
              Excel
            </button>
          </div>
        </div>
      </div>
    </>
  );
};
