  { empId: 'NIT/0002', title: 'Dr.', firstName: 'Indrani', lastName: '(Dey) Sarkar', deptCode: 'PHYSICS', rawDesignation: 'Associate Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0030', title: 'Dr.', firstName: 'Nikhilesh', lastName: 'Sil', deptCode: 'MATH', rawDesignation: 'Associate Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0070', title: 'Mrs.', firstName: 'Debrupa', lastName: '(Pal) Palit', deptCode: 'CA', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0087', title: 'Ms.', firstName: 'Rajasi', lastName: 'Ray', deptCode: 'ENGLISH', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0112', title: 'Dr.', firstName: 'Sagarika', lastName: 'Chowdhury', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0118', title: 'Dr.', firstName: 'Koushik', lastName: 'Karmakar', deptCode: 'CST', rawDesignation: 'Assistant Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0159', title: 'Mrs.', firstName: 'Subhasree', lastName: 'Bhattacharjee (Choudhury)', deptCode: 'CA', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0168', title: 'Dr.', firstName: 'Jayanta', lastName: 'Pal', deptCode: 'CSBS', rawDesignation: 'Associate Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0170', title: 'Dr.', firstName: 'Sarbani', lastName: 'Ganguly', deptCode: 'CHEMISTRY', rawDesignation: 'Assistant Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0171', title: 'Dr.', firstName: 'Sriparna', lastName: 'Guha', deptCode: 'BA', rawDesignation: 'Assistant Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0184', title: 'Mrs.', firstName: 'Rupa', lastName: 'Saha', deptCode: 'CA', rawDesignation: 'Assistant Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0209', title: 'Dr.', firstName: 'Chandrima', lastName: 'Chakrabarti', deptCode: 'CSE - DS', rawDesignation: 'Associate Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0221', title: 'Dr.', firstName: 'Dhananjay', lastName: 'Kr. Tripathi', deptCode: 'PHYSICS', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0227', title: 'Dr.', firstName: 'Soumen', lastName: 'Ghosh', deptCode: 'IT', rawDesignation: 'Assistant Professor Dpty. (COE)', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0238', title: 'Ms.', firstName: 'Dipu', lastName: 'Mistry', deptCode: 'EE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0241', title: 'Mr.', firstName: 'Soumen', lastName: 'Pal', deptCode: 'ECE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0244', title: 'Dr.', firstName: 'Bidyut', lastName: 'Kumar Medya', deptCode: 'IT', rawDesignation: 'Professor & COE', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0247', title: 'Dr.', firstName: 'Sandhya', lastName: 'Pattanayak', deptCode: 'ECE', rawDesignation: 'Associate Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0248', title: 'Ms.', firstName: 'Sharmistha', lastName: 'Basu', deptCode: 'ENGLISH', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0250', title: 'Mr.', firstName: 'Rajkumar', lastName: 'Banerjee', deptCode: 'CIVIL', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0251', title: 'Dr.', firstName: 'Kaushik', lastName: 'Sarkar', deptCode: 'ECE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0252', title: 'Dr.', firstName: 'Susmita', lastName: 'Karan', deptCode: 'PHYSICS', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0254', title: 'Dr.', firstName: 'Pranab', lastName: 'Hazra', deptCode: 'ECE', rawDesignation: 'Assistant Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0263', title: 'Ms.', firstName: 'Sujata', lastName: 'Kundu', deptCode: 'IT', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0268', title: 'Mr.', firstName: 'Anirban', lastName: 'Bhar', deptCode: 'IT', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0276', title: 'Dr.', firstName: 'Rupa', lastName: 'Bhattacharyya (Chakrabotry)', deptCode: 'CHEMISTRY', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0282', title: 'Ms.', firstName: 'Arpita', lastName: 'Barman', deptCode: 'ECE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0283', title: 'Dr.', firstName: 'Suchismita', lastName: 'Maiti - (Biswas)', deptCode: 'IT', rawDesignation: 'Associate Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0342', title: 'Dr.', firstName: 'Ashifuddin', lastName: 'Mondal', deptCode: 'CSE', rawDesignation: 'Associate Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0372', title: 'Dr.', firstName: 'Anukul', lastName: 'Maity', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0385', title: 'Ms.', firstName: 'Swati', lastName: '( Banerjee) Barui', deptCode: 'ECE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0410', title: 'Mr.', firstName: 'Abhijit', lastName: 'Ghosh', deptCode: 'ECE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0414', title: 'Dr.', firstName: 'Arkendu', lastName: 'Mitra', deptCode: 'EE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0415', title: 'Ms.', firstName: 'Kamalika', lastName: 'Benerjee', deptCode: 'EE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0422', title: 'Dr.', firstName: 'Bansari', lastName: 'Deb Majumder', deptCode: 'EE', rawDesignation: 'Associate Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0456', title: 'Dr.', firstName: 'Sangita', lastName: '(Roy) Biswas', deptCode: 'ECE', rawDesignation: 'Associate Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0468', title: 'Ms.', firstName: 'Debjani', lastName: 'Chakraborty', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0472', title: 'Mr.', firstName: 'Sudhangshu', lastName: 'Sarkar', deptCode: 'EE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0473', title: 'Mr.', firstName: 'Abhipriya', lastName: 'Halder', deptCode: 'CIVIL', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0497', title: 'Mr.', firstName: 'Soumya', lastName: 'Bhattacharyya', deptCode: 'IT', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0498', title: 'Dr.', firstName: 'Shubhendu', lastName: 'Banerjee', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0512', title: 'Dr.', firstName: 'Moupali', lastName: 'Roy', deptCode: 'ECE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0529', title: 'Ms.', firstName: 'Subhra', lastName: 'Mukherjee', deptCode: 'EE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0540', title: 'Ms.', firstName: 'Priyanjali', lastName: 'Mukherjee', deptCode: 'EE', rawDesignation: 'Assistant Professor Asst. COE', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0620', title: 'Dr.', firstName: 'Susmita', lastName: 'Das', deptCode: 'ECS', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0638', title: 'Mr.', firstName: 'Ankesh', lastName: 'Samanta', deptCode: 'ME', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0639', title: 'Mr.', firstName: 'Akhtarujjaman', lastName: 'Sarkar', deptCode: 'ME', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0642', title: 'Mr.', firstName: 'Arya', lastName: 'Banerjee', deptCode: 'CIVIL', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0654', title: 'Mr.', firstName: 'Arghya', lastName: 'Gupta', deptCode: 'ME', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0696', title: 'Mr.', firstName: 'Pallav', lastName: 'Dutta', deptCode: 'EE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0727', title: 'Dr.', firstName: 'Sumanta', lastName: 'Kundu', deptCode: 'EE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0730', title: 'Ms.', firstName: 'Debopriya', lastName: 'Dey', deptCode: 'MATH', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0731', title: 'Dr.', firstName: 'Sumit', lastName: 'Chabri', deptCode: 'ME', rawDesignation: 'Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0740', title: 'Dr.', firstName: 'Abhishek', lastName: 'Hazra', deptCode: 'CIVIL', rawDesignation: 'Assistant Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0744', title: 'Ms.', firstName: 'Anasuya', lastName: 'Mondal', deptCode: 'CIVIL', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0751', title: 'Dr.', firstName: 'Biswajit', lastName: 'Halder', deptCode: 'EE', rawDesignation: 'Associate Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0754', title: 'Dr.', firstName: 'Shilpi', lastName: 'Pal', deptCode: 'MATH', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0755', title: 'Ms.', firstName: 'Payel', lastName: 'Mondal', deptCode: 'MATH', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0760', title: 'Dr.', firstName: 'Bishaljit', lastName: 'Paul', deptCode: 'EE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0764', title: 'Mr.', firstName: 'Somnath', lastName: 'Chakraborty', deptCode: 'BA', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0765', title: 'Ms.', firstName: 'Sanghamitra', lastName: 'Layek', deptCode: 'ECS', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0772', title: 'Dr.', firstName: 'Shambhu', lastName: 'Nath Saha', deptCode: 'IT', rawDesignation: 'Associate Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0780', title: 'Dr.', firstName: 'Sourav', lastName: 'Saha', deptCode: 'CSE', rawDesignation: 'Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0781', title: 'Dr.', firstName: 'Jagannibas', lastName: 'Paul Choudhury', deptCode: 'CSE', rawDesignation: 'Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0791', title: 'Dr.', firstName: 'Papri', lastName: 'Ghosh', deptCode: 'CSE', rawDesignation: 'Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/0792', title: 'Mr.', firstName: 'Amit', lastName: 'Nigam', deptCode: 'ECE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1296', title: 'Ms.', firstName: 'Aparajita', lastName: 'Paul', deptCode: 'ENGLISH', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1300', title: 'Mr.', firstName: 'Debanjan', lastName: 'Mitra', deptCode: 'IT', rawDesignation: 'Assistant Professor (Training)', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1302', title: 'Mr.', firstName: 'Apurba', lastName: 'Ghosh', deptCode: 'MATH', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1308', title: 'Dr.', firstName: 'Swastika', lastName: 'Chakraborty (Mukhopadhyay)', deptCode: 'ECE', rawDesignation: 'Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1312', title: 'Dr.', firstName: 'Subimal', lastName: 'Roy Barman', deptCode: 'EE', rawDesignation: 'Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1313', title: 'Dr.', firstName: 'Pushpita', lastName: 'Roy', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1317', title: 'Ms.', firstName: 'Marcelline', lastName: 'Salome Gomes', deptCode: 'BA', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1321', title: 'Dr.', firstName: 'Sibapriya', lastName: 'Mukherjee', deptCode: 'CIVIL', rawDesignation: 'Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1368', title: 'Mr.', firstName: 'Subhankar', lastName: 'Dey', deptCode: 'CIVIL', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1369', title: 'Ms.', firstName: 'Debasmita', lastName: 'Sen', deptCode: 'ENGLISH', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1373', title: 'Ms.', firstName: 'Prianka', lastName: 'Dey', deptCode: 'CSBS', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1374', title: 'Dr.', firstName: 'Suman', lastName: 'Kumar Bhattachryya', deptCode: 'IT', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1379', title: 'Mr.', firstName: 'Sudip', lastName: 'Das', deptCode: 'CA', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1381', title: 'Dr.', firstName: 'Puja', lastName: 'Supakar', deptCode: 'MATH', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1385', title: 'Ms.', firstName: 'Bingshati', lastName: 'Mondal', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1397', title: 'Ms.', firstName: 'Swarnali', lastName: 'Daw', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1398', title: 'Dr.', firstName: 'Bikas', lastName: 'Mondal', deptCode: 'ECS', rawDesignation: 'Assistant Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1399', title: 'Dr.', firstName: 'Neepa', lastName: 'Biswas', deptCode: 'IT', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1418', title: 'Ms.', firstName: 'Jayita', lastName: 'Pal', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1443', title: 'Mr.', firstName: 'Avishek', lastName: 'Nath', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1445', title: 'Ms.', firstName: 'Ipsita', lastName: 'Dalui', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1450', title: 'Mr.', firstName: 'Tanmoy', lastName: 'Ghosh', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1458', title: 'Mr.', firstName: 'Mrinmoy', lastName: 'Guria', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1466', title: 'Ms.', firstName: 'Sohinee', lastName: 'Mondal', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1468', title: 'Mr.', firstName: 'Tathagata', lastName: 'Chatterjee', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1469', title: 'Ms.', firstName: 'Namrata', lastName: 'Pandey', deptCode: 'ENGLISH', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1478', title: 'Ms.', firstName: 'Ritwika', lastName: 'Mukherjee', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1479', title: 'Ms.', firstName: 'Suseta', lastName: 'Datta', deptCode: 'CA', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1484', title: 'Mr.', firstName: 'Arindam', lastName: 'Das', deptCode: 'CSE - DS', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1487', title: 'Dr.', firstName: 'Bimal', lastName: 'Datta', deptCode: 'CSE', rawDesignation: 'Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1488', title: 'Ms.', firstName: 'Pritusna', lastName: 'Banik', deptCode: 'CST', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1491', title: 'Ms.', firstName: 'Dishani', lastName: 'Roy', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1492', title: 'Ms.', firstName: 'Ritama', lastName: 'Sharma', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1493', title: 'Mr.', firstName: 'Dipayan', lastName: 'Das', deptCode: 'IT', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1499', title: 'Mr.', firstName: 'Gopal', lastName: 'Pramanik', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1502', title: 'Dr.', firstName: 'Dipankar', lastName: 'Saha', deptCode: 'ECE', rawDesignation: 'Associate Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1522', title: 'Dr.', firstName: 'Nabanita', lastName: 'Das', deptCode: 'CSE - DS', rawDesignation: 'Associate Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1523', title: 'Mr.', firstName: 'Alok', lastName: 'Nath Pal', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1529', title: 'Dr.', firstName: 'Sudakshina', lastName: 'Mandal', deptCode: 'CA', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1534', title: 'Mr.', firstName: 'Debabrata', lastName: 'Maity', deptCode: 'IT', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1551', title: 'Dr.', firstName: 'Kishalay', lastName: 'Bairagi', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1552', title: 'Dr.', firstName: 'Maitrayee', lastName: 'Chakrabarty', deptCode: 'EE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1556', title: 'Dr.', firstName: 'Soma', lastName: 'Chatterjee', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1557', title: 'Ms.', firstName: 'Karobi', lastName: 'Sarkar', deptCode: 'CST', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1558', title: 'Mr.', firstName: 'Naren', lastName: 'Debnath', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1561', title: 'Mr.', firstName: 'Pratap', lastName: 'Chandra Roy', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1562', title: 'Ms.', firstName: 'Promita', lastName: 'Dey', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1563', title: 'Mr.', firstName: 'Sudip', lastName: 'Hansda', deptCode: 'CSBS', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1564', title: 'Mr.', firstName: 'Souvik', lastName: 'Sharma', deptCode: 'CIVIL', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1566', title: 'Dr.', firstName: 'Parthasarathi', lastName: 'De', deptCode: 'CSE - AIML', rawDesignation: 'Associate Professor-HOD', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1567', title: 'Ms.', firstName: 'Shristi', lastName: 'Seal', deptCode: 'CSBS', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1583', title: 'Ms.', firstName: 'Mousumi', lastName: 'Mitra', deptCode: 'CSE - DS', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1587', title: 'Ms.', firstName: 'Mouli', lastName: 'Das', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1590', title: 'Mr.', firstName: 'Abhishek', lastName: 'Banerjee', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1591', title: 'Ms.', firstName: 'Pubali', lastName: 'Maiti', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1592', title: 'Ms.', firstName: 'Ankita', lastName: 'Barua', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1595', title: 'Mr.', firstName: 'Biswajit', lastName: 'Patra', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1598', title: 'Mr.', firstName: 'Debarshi', lastName: 'Bandyopadhyay', deptCode: 'CSE - AIML', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1599', title: 'Dr.', firstName: 'Subhabrata', lastName: 'Roy', deptCode: 'ECE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1601', title: 'Dr.', firstName: 'Sujit', lastName: 'Saha', deptCode: 'ME', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1615', title: 'Mr.', firstName: 'Arvin', lastName: 'Bera', deptCode: 'CSE - DS', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
  { empId: 'NIT/1616', title: 'Mr.', firstName: 'Archi', lastName: 'Choudhary', deptCode: 'CSE', rawDesignation: 'Assistant Professor', createdBy: process.env.SUPER_ADMIN_NAME },
